#!/usr/bin/env bash

# Source base functions
source "$(dirname "${BASH_SOURCE[0]}")/base"

setup() {
    [[ "$(podman machine list)" != *"qumran"* ]] && podman machine init --playbook=development.yml qumran
}

start() {
    local answer
    answer="$(podman machine list)"

    if [[ "$answer" == *"qumran"* && "$answer" != *"qumran*"*"Currently running"* ]]; then
        podman machine start qumran --no-info
        podman machine ssh qumran "ansible-playbook playbook.yaml"
    fi
}

stop() {
    if [[ "$(podman machine list)" == *"qumran*"*"Currently running"* ]]; then
        podman machine stop qumran
    fi
}

destroy() {
    local answer
    answer="$(podman machine list)"

    if [[ "$answer" == *"qumran"* && "$answer" == *"qumran*"*"Currently running"* ]]; then
        podman machine stop qumran
        podman machine rm qumran
        exit 0
    fi

    [[ "$answer" == *"qumran"* ]] && podman machine rm qumran
}

execute_destroy() {
    log_info "Destroying local development"
    destroy
}

execute_setup() {
    log_info "Setting-up local development"
    setup
}

execute_start() {
    log_info "Starting local development"
    start
}

execute_stop() {
    log_info "Stopping local development"
    stop
}
